# frozen_string_literal: true
#
# scripts/lib/opl_entity_extractor.rb
#
# V7 OPL entity-name extractor. Reuses V6's EBNF→treetop translator;
# the OPL parse tree's nodes are tagged with `__rule__` (added by
# scripts/lib/ebnf_to_treetop.rb's emitter), allowing us to identify
# which EBNF rule produced each node.
#
# The pin file `tools/iso-19450-opd-coherence.txt` lists, one per line,
# the mapping:
#
#   <entity-introducing-rule> : <name-bearing-rule>
#
# where both names are post-sanitization EBNF rule names (hyphens
# converted to underscores). For each parse-tree node tagged with an
# entity-introducing-rule, the extractor walks the subtree to find
# every descendant node tagged with the corresponding name-bearing-
# rule and collects its `text_value` (whitespace-trimmed) into the
# returned set.
#
# Required by:
#   - scripts/v7-opd-opl-coherence.rb
#   - tests/test-v7-extractor.rb

require 'rexml/document'
require 'set'

module OPLEntityExtractor
  module_function

  # Marker class on opd.svg <text> elements that name an OPM entity.
  # opl-to-svg.rb tags every node-label <text> with this class; edge
  # labels (relation phrases) are deliberately untagged so V7 ignores
  # them. Hand-authored SVGs MUST tag entity-name text elements with
  # this class for V7 to recognise them.
  ENTITY_CLASS = 'opm-entity'

  # Extract the set of entity-name strings declared by an opd.svg's
  # <text class="opm-entity"> elements (whitespace-trimmed; empty
  # strings dropped). Raises if the SVG contains no entity-classed
  # text — that's a sign the SVG was either generated by a stale
  # tool or hand-authored without the convention.
  def svg_entity_text(svg_text)
    doc   = REXML::Document.new(svg_text)
    texts = []
    doc.each_element("//text[@class='#{ENTITY_CLASS}']") do |el|
      texts << el.text.to_s.strip if el.text
    end
    # XPath above only matches when class is exactly "opm-entity".
    # Some generators emit class="foo opm-entity" (multi-class). Walk
    # all <text> and check tokenised class membership for completeness.
    doc.each_element('//text') do |el|
      cls = el.attributes['class']
      next unless cls
      next unless cls.split(/\s+/).include?(ENTITY_CLASS)
      txt = el.text.to_s.strip
      texts << txt unless txt.empty?
    end
    Set.new(texts).reject(&:empty?).to_set
  end

  # Parse the coherence pin file's text into
  #   { 'entity_introducing_rule' => 'name_bearing_rule', ... }
  #
  # Lines starting with `#` and blank lines are ignored. Each non-
  # comment line MUST match `<rule> : <rule>`. The names are written
  # in their EBNF form (hyphens permitted); they are sanitized
  # (hyphens → underscores) to match the rule names in V6's emitted
  # treetop grammar.
  def parse_coherence(text)
    productions = {}
    text.each_line.with_index(1) do |raw, line_no|
      line = raw.strip
      next if line.empty? || line.start_with?('#')
      unless line =~ /\A([A-Za-z_][\w-]*)\s*:\s*([A-Za-z_][\w-]*)\z/
        raise "tools/iso-19450-opd-coherence.txt:#{line_no}: invalid line #{raw.inspect} " \
              '(expected "<entity-rule> : <name-rule>")'
      end
      productions[Regexp.last_match(1).tr('-', '_')] = Regexp.last_match(2).tr('-', '_')
    end
    raise 'tools/iso-19450-opd-coherence.txt has no production mappings' if productions.empty?
    productions
  end

  # Walk a treetop parse tree and yield every node.
  def walk(node, &blk)
    yield node
    return unless node.respond_to?(:elements) && node.elements
    node.elements.each { |e| walk(e, &blk) }
  end

  # The rule a node was produced by, or nil if the node is from an
  # untagged source (terminal, intermediate sequence, etc.).
  def node_rule(node)
    node.respond_to?(:__rule__) ? node.__rule__ : nil
  end

  # Extract the set of entity-name strings from an OPL parse tree.
  # `productions` is the hash returned by `parse_coherence`.
  def entity_names(parse_tree, productions)
    entities = Set.new
    walk(parse_tree) do |node|
      rule = node_rule(node)
      next unless rule && (name_rule = productions[rule])
      walk(node) do |inner|
        next unless node_rule(inner) == name_rule
        text = inner.text_value.to_s.strip
        entities << text unless text.empty?
      end
    end
    entities
  end
end
