#!/usr/bin/env bash
#
# v2-arc42-build.sh
#
# Drives the arc42-generator Docker pipeline against the wiki's local
# AsciiDoc sources, then scans the build log for cmark / image-validation
# warnings (the generator treats these as non-fatal; V2 does not).
#
# Strategy: stage src/arc42/ over the generator's pinned arc42-template
# submodule's EN/ tree, run `docker compose up`, then restore the submodule
# to its pinned state. This is the only way to get our edits processed,
# since the generator only reads from its own submodule path.

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly GEN_DIR="$REPO_ROOT/vendor/arc42-generator"
readonly GEN_TEMPLATE="$GEN_DIR/arc42-template"
readonly GEN_EN="$GEN_TEMPLATE/EN"
readonly ARC42_TEMPLATE_PIN_FILE="$REPO_ROOT/tools/arc42-template-pin.txt"
readonly LOCAL_SRC="$REPO_ROOT/src/arc42"
readonly BUILD_LOG="$REPO_ROOT/build/v2-arc42-build.log"

# Pattern set must be revised when the arc42-generator submodule pin moves.
readonly CMARK_WARN_RE='cmark.*(error|warning|invalid)'
readonly IMAGE_WARN_RE='(image (not found|missing|unresolved)|broken image reference)'

err()  { printf 'V2: ERROR: %s\n' "$*" >&2; }
info() { printf 'V2: %s\n' "$*"; }

mkdir -p "$(dirname "$BUILD_LOG")"

# ---- restore the generator's submodule on any exit ----------------------
# After staging our edits, we must restore the arc42-template submodule to
# the SHA we pinned in tools/arc42-template-pin.txt — both `git checkout --`
# and the build pipeline can mutate it.
restore_submodule() {
    if [ -d "$GEN_TEMPLATE/.git" ] || [ -f "$GEN_TEMPLATE/.git" ]; then
        ( cd "$GEN_TEMPLATE" \
            && git checkout --quiet -- . 2>/dev/null \
            && git clean --quiet -fd 2>/dev/null \
            && if [ -f "$ARC42_TEMPLATE_PIN_FILE" ]; then \
                   PIN=$(tr -d '[:space:]' < "$ARC42_TEMPLATE_PIN_FILE"); \
                   [ -n "$PIN" ] && git checkout --quiet "$PIN" 2>/dev/null; \
               fi ) || true
    fi
}
trap restore_submodule EXIT

# ---- pre-flight ---------------------------------------------------------

[ -d "$GEN_DIR" ] || { err "vendor/arc42-generator missing"; exit 2; }
[ -d "$GEN_EN" ]  || { err "$GEN_EN missing (run: git submodule update --init --recursive)"; exit 2; }
[ -d "$LOCAL_SRC/adoc" ] || { err "src/arc42/adoc/ missing"; exit 2; }
[ -f "$GEN_EN/adoc/01_introduction_and_goals.adoc" ] \
    || { err "expected layout EN/adoc/ not present in arc42-template — run scripts/install-tools.sh to enforce the pin"; exit 2; }

# ---- clear stale generator build outputs --------------------------------

# Gradle/docker's incremental-build cache has historically retained stale
# per-chapter MD outputs when source AsciiDoc changed in ways the cache
# didn't recognize as inputs (boundary attribute insertions, passthrough
# conversions, narrative-only additions). Force a clean rebuild by nuking
# the generator's build dir before staging + invocation. Idempotent: the
# directory is regenerated by every successful docker run.
if [ -d "$GEN_DIR/build" ]; then
    info "clearing stale generator build cache: $GEN_DIR/build"
    rm -rf "$GEN_DIR/build"
fi

# ---- stage local sources over upstream EN -------------------------------

info "staging src/arc42/adoc/ over $GEN_EN/adoc/"
# We do NOT overwrite arc42-template.adoc here: src/arc42/arc42-template.adoc
# is for direct asciidoctor invocation against the wiki layout, while the
# generator must use its own umbrella file (which references include::adoc/...
# relative to its own EN/ root).
for f in "$LOCAL_SRC/adoc"/*.adoc; do
    cp "$f" "$GEN_EN/adoc/$(basename "$f")"
done
if [ -d "$LOCAL_SRC/images" ] && [ -n "$(ls -A "$LOCAL_SRC/images" 2>/dev/null)" ]; then
    mkdir -p "$GEN_EN/images"
    cp "$LOCAL_SRC/images"/*.svg "$GEN_EN/images/" 2>/dev/null || true
fi

# ---- invoke generator's documented entry point --------------------------

# NOTE: we deliberately skip build-arc42.sh (the docker-compose `command:`)
# because that wrapper does `rm -rf arc42-template; git submodule update`,
# which (a) wipes our staged edits and (b) fails inside our nested-submodule
# git layout where the inner submodule's gitlink resolves to a path outside
# the docker mount. We invoke the underlying Groovy build directly with the
# format scoped to gitHubMarkdownMP — the only output we consume.
info "running: docker compose run -- groovy build.groovy --format=gitHubMarkdownMP (log: $BUILD_LOG)"
( cd "$GEN_DIR" \
    && docker compose run --rm --build \
       --entrypoint groovy arc42-builder build.groovy --format=gitHubMarkdownMP ) \
    > "$BUILD_LOG" 2>&1 || {
    err "docker compose run exited non-zero; tail of log:"
    tail -30 "$BUILD_LOG" >&2
    exit 1
}

# ---- post-build log scan for cmark / image warnings ---------------------

CMARK_HITS=$(grep -E -i  "$CMARK_WARN_RE" "$BUILD_LOG" | grep -v -E '^#[0-9]+ pull|^# step' || true)
IMAGE_HITS=$(grep -E -i "$IMAGE_WARN_RE"  "$BUILD_LOG" || true)

if [ -n "$CMARK_HITS" ] || [ -n "$IMAGE_HITS" ]; then
    err "post-build log scan found warnings"
    [ -n "$CMARK_HITS" ] && { printf 'V2: cmark warnings:\n%s\n' "$CMARK_HITS" >&2; }
    [ -n "$IMAGE_HITS" ] && { printf 'V2: image warnings:\n%s\n' "$IMAGE_HITS" >&2; }
    exit 1
fi

# ---- verify per-chapter markdown output exists --------------------------

# Output structure: build/EN/gitHubMarkdownMP/{plain,with-help}/...
# We consume the `plain` variant (no embedded arc42 help blocks).
readonly OUT_DIR="$GEN_DIR/build/EN/gitHubMarkdownMP/plain"
[ -d "$OUT_DIR" ] || {
    err "expected output dir $OUT_DIR not present after build"
    info "build/EN/ contains:"
    ls -la "$GEN_DIR/build/EN/" 2>&1 | sed 's/^/  /' >&2 || true
    exit 1
}

missing=0
for adoc in "$LOCAL_SRC/adoc"/*.adoc; do
    base=$(basename "$adoc" .adoc)
    md="$OUT_DIR/${base}.md"
    if [ ! -s "$md" ]; then
        err "missing or empty: $md"
        missing=$((missing + 1))
    fi
done
[ "$missing" -eq 0 ] || exit 1

info "PASS"
