#!/usr/bin/env bash
#
# v3-structurizr.sh
#
# Phase 1: structurizr.war validate    (parser conformance)
# Phase 2: structurizr.war export -svg (renders each view to src/arc42/images/)
# Phase 3: every defined view has a matching SVG on disk
# Phase 4: every image::{key}.svg[] reference in src/arc42/adoc/ resolves
#          to a view key actually defined in src/c4/workspace.dsl

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly WAR="$REPO_ROOT/tools/structurizr.war"
readonly WORKSPACE="$REPO_ROOT/src/c4/workspace.dsl"
readonly IMAGES_DIR="$REPO_ROOT/src/arc42/images"
readonly ADOC_DIR="$REPO_ROOT/src/arc42/adoc"
readonly PLAYWRIGHT_BROWSERS="$REPO_ROOT/tools/playwright-browsers"

err()  { printf 'V3: ERROR: %s\n' "$*" >&2; }
info() { printf 'V3: %s\n' "$*"; }

[ -f "$WAR" ]      || { err "$WAR missing (run scripts/install-tools.sh)"; exit 2; }
[ -f "$WORKSPACE" ] || { err "$WORKSPACE missing"; exit 2; }
mkdir -p "$IMAGES_DIR"

# ---- Phase 1: validate --------------------------------------------------

info "validating $WORKSPACE"
java -jar "$WAR" validate -workspace "$WORKSPACE" || {
    err "structurizr validate exited non-zero"
    exit 1
}

# ---- Phase 2: export ----------------------------------------------------
#
# Note: structurizr writes exports to the workspace file's directory by
# default; -output overrides that. Existing SVGs in IMAGES_DIR are left in
# place if no view of the same key is exported (no auto-clean), so we wipe
# the directory before export to drop stale outputs from removed views.
#
# Important: structurizr's SVG exporter always launches Playwright's
# headless Chromium, even for workspaces with zero views. Skip the export
# step entirely when no view keys are defined — there's nothing to render
# and the browser launch is a system-dependency burden that's irrelevant
# until views exist.

info "wiping stale SVGs in $IMAGES_DIR"
find "$IMAGES_DIR" -maxdepth 1 -name '*.svg' -delete

# Heuristic for "workspace declares any view": a view-introducing keyword
# (systemContext, container, component, dynamic, deployment, filtered,
# image) appears at start-of-line inside the file. Better than parsing
# `key "..."` because the DSL accepts the key as a positional argument
# AND lacks a `key` property inside view blocks.
if grep -E -q '^\s*(systemContext|container|component|dynamic|deployment|filtered|image)\s+[A-Za-z_]' "$WORKSPACE"; then
    info "exporting views to $IMAGES_DIR"
    mkdir -p "$PLAYWRIGHT_BROWSERS"
    PLAYWRIGHT_BROWSERS_PATH="$PLAYWRIGHT_BROWSERS" \
    java -jar "$WAR" export \
         -workspace "$WORKSPACE" \
         -format svg \
         -output "$IMAGES_DIR" || {
        err "structurizr export exited non-zero"
        exit 1
    }
else
    info "workspace defines no views; skipping export"
fi

# ---- Phase 2.5: post-process exported SVGs ------------------------------
#
# The Structurizr exporter writes two artifacts per view:
#   <key>.svg        the diagram itself
#   <key>-key.svg    the legend/key (autogenerated, never referenced
#                    from arc42 chapters or the wiki frame)
#
# It also injects a "diagram description" footer into every <key>.svg
# containing the view's description AND a generation timestamp of the
# form "Tuesday, May 5, 2026 at 12:04 PM Coordinated Universal Time".
# The timestamp varies on every export and is the sole source of the
# per-build C4-SVG churn this repo has carried since the C4 sources
# landed. This phase removes:
#
#   1. The orphan -key.svg legend files (not referenced anywhere).
#   2. The timestamp <text> elements from every <key>.svg.
#
# Removing the timestamps makes the SVGs deterministic across runs
# (Stage 5 idempotence holds without ride-along SVG diffs); removing
# the keys keeps images/ free of unused files. The view description
# footer is preserved (it carries authorial intent, not build state).

if [ -d "$IMAGES_DIR" ]; then
    info "post-processing exported SVGs"
    find "$IMAGES_DIR" -maxdepth 1 -name '*-key.svg' -delete

    # Strip the structurizr-injected metadata footer (timestamp, title,
    # and description). All three live in the same shape:
    #
    #   <g id="j_87" transform="..."><g id="v-896"><text ...font-size="X">
    #     <tspan ...>TEXT</tspan></text></g></g>
    #
    # font-size 24px is the description (prose, multi-line — also the
    # timestamp; same font); font-size 36px is the title. Diagram nodes
    # use different font sizes (33.6px for deployment-node titles,
    # 16.8px for technology labels, 14px for relationship labels).
    # The metadata sits at the bottom of structurizr's original canvas
    # regardless of content extent, so it produces wasted vertical
    # space when autoLayout has compacted the diagram. Strip all three
    # blocks; the chapter prose already carries title and description.
    find "$IMAGES_DIR" -maxdepth 1 -name '*.svg' | while read -r svg; do
        sed -i -E 's@<g[^>]*id="j_[0-9]+"[^>]*><g[^>]*id="v-[0-9]+"><text[^>]*font-size="(24px|36px)"[^>]*><tspan[^>]*>[^<]+</tspan></text></g></g>@@g' "$svg"
    done

    # Crop each SVG's viewBox to the actual content bounding box plus
    # padding. Structurizr emits a fixed canvas per view (e.g.,
    # 2000x2000 for the deployment views) regardless of how much room
    # the autoLayout actually consumed; tightened layouts produce small
    # content in the top-left corner of an oversized canvas, rendering
    # as "jumbled boxes in the corner of the frame" on the wiki. The
    # crop forces the SVG to size itself to what's actually drawn.
    info "cropping SVG viewBoxes to content extent"
    find "$IMAGES_DIR" -maxdepth 1 -name '*.svg' | while read -r svg; do
        bundle exec ruby -r"$REPO_ROOT/scripts/lib/svg_crop" \
            -e "SvgCrop.crop_file(ARGV[0])" "$svg" >/dev/null \
            || { err "viewBox crop failed for $svg"; exit 1; }
    done
fi

# ---- Phase 3 + 4: derive view keys from exported SVG filenames ---------
# The exporter writes `<viewKey>.svg` per view. This is the authoritative
# source of "what views the workspace produced", more reliable than
# trying to re-parse the DSL outside the structurizr parser. Phase 3
# (every defined view has an SVG) is enforced by the export step itself
# exiting non-zero on any failure. Phase 4 (every image:: reference
# resolves) compares AsciiDoc references against the exported set.

mapfile -t EXPORTED_KEYS < <(
    find "$IMAGES_DIR" -maxdepth 1 -name '*.svg' -printf '%f\n' \
        | sed 's/\.svg$//' \
        | sort -u
)

unresolved=()
if [ -d "$ADOC_DIR" ]; then
    while IFS=: read -r file lineno match; do
        [ -z "$file" ] && continue
        ref=$(printf '%s' "$match" | sed -E 's/.*image::([^[]+)\.svg\[.*/\1/')
        # Only enforce for c4-* references; non-c4 SVGs may be hand-authored.
        case "$ref" in
            c4-*)
                if ! printf '%s\n' "${EXPORTED_KEYS[@]:-}" | grep -Fxq "$ref"; then
                    unresolved+=("$file:$lineno: image::${ref}.svg[]")
                fi
                ;;
        esac
    done < <(grep -E -n -H 'image::[^[]+\.svg\[' "$ADOC_DIR"/*.adoc 2>/dev/null || true)
fi

if [ "${#unresolved[@]}" -gt 0 ]; then
    err "AsciiDoc image:: references that do not match any exported view key:"
    for u in "${unresolved[@]}"; do printf '  - %s\n' "$u" >&2; done
    exit 1
fi

info "PASS (${#EXPORTED_KEYS[@]} view(s))"
